### ISSUE TITLE
Fallback to 0.3 discovery

### ISSUE THREAD

**Issue by evanp** [pubsubhubbub/PubSubHubbub#1]
It would be nice if discovery could fall back to the 0.3 mechanism for certain data types, if the expected headers aren't there.
- For Atom (application/atom+xml), look for `<link rel="hub">` in the feed.
- For RSS (application/rss+xml), look for `<atom:link rel="hub">` in the feed.

**Comment by superfeedr** [comment]
I'm not sure this belongs to the spec. I really really want to make the spec easier. But it's obvious to me that a good client should be able to fall back to 0.3 mechanisms.
For me it's more a matter of implementation than a matter of spec.

**Comment by ralphm** [comment]
I suggest using SHOULD instead of MUST for HTTP Link header discovery, and then say something like:

  Hub implementations MAY try alternative sources to establish the location of hubs for a particular resource, including HTML and Atom Link elements as defined in appendices A and B of RFC 5988.

**Comment by superfeedr** [comment]
@ralphm Feel free to send a pull request :) I'm not sure where you want me to put that in `pubsubhubbub-core-0.4.xml`in the `future`branch.

**Comment by ralphm** [comment]
I was also tempted to include some of the 'best practice' text on hubs performing heuristics for resource equivalence. Why was that removed? I understand if it is REQUIRED to include the link header with rel=self, this problem doesn't exist. In reality, though, this might still be good advice.
