### ISSUE TITLE
Do we need arbitrary data types?

### ISSUE THREAD

**Issue by evanp** [pubsubhubbub/PubSubHubbub#10]
I want to double-check that we're doing the right thing by supporting arbitrary data types.

Atom, RSS 1.0, RSS 2.0 and Activity Streams are all feed formats that represent _changes_. That's the whole point of these syndication formats.

Changes to other kinds of documents and resources -- images, HTML pages, video and audio -- may be better represented with these document types.

So, rather than using PuSH for file like http://example.net/images/file.png, instead have a related Atom feed (or JSON feed, or RSS feed) that represents the history of that file.

**Comment by superfeedr** [comment]
We do need arbitrary data types. We have had customer asking for even HTML pages! Generally, today's new hotness is Json, but who knows what it is going to be tomorrow: YAML, raw text... or even non-atom XML.

I understand Atom, RSS and AS to represent change, but I would argue that Atom did represent change well enough with it's namespaces and there was no real need (feature wise) to do AS Json. Yet, that's what that AS community is pushing these days.

I posted a small rant a couple weeks ago saying we need SUBSCRIBE as much as we have GET, POST, PUT and delete in HTML.

**Comment by ralphm** [comment]
Agreed with @superfeedr here. If you look at the stuff I built over at Mediamatic, each and every _thing_ has its own XMPP pubsub feed to subscribe to changes to that individual thing. Upon each change, a notification would just have the thing rendered as an Atom Entry Document. Microblog entries don't really change all that much after being created, but other things do.

**Comment by evanp** [comment]
Cool. I'm going to close this issue, then.
