### ISSUE TITLE
clean up the repo

### ISSUE THREAD

**Issue by pfefferle** [pubsubhubbub/PubSubHubbub#18]
I think it would be more helpfull if the pubsubhubbub folder would only include the different specs because the code is a bit old and this could be a bit confusing. What about asking some people to move there libs to this repo to have a central code space (like the openid repo https://github.com/openid)?

**Comment by julien51** [comment]
That's a very good point. What I'll do for now is actualy put the code in some other branch for now, jst in case someone thinks it's a bad idea to remove it from there.

**Comment by pfefferle** [comment]
Cool! What about asking some people to move over their libs? So it's easier for developers to implement pubsubhubub...

**Comment by julien51** [comment]
That's a great point. We can at least fork them under the organisation (so that they're easy to point to).  Feel free to send the ones you're thinking about!
Thanks

**Comment by pfefferle** [comment]
https://github.com/pfefferle/wordpress-pubsubhubbub :)

**Comment by julien51** [comment]
Forked!

**Comment by pfefferle** [comment]
What do you think about using the gh-pages branch as master? that means you don't have to update to branches if you update or add a spec?

**Comment by julien51** [comment]
That's an idea, but I think that for Github to update http://pubsubhubbub.github.io/PubSubHubbub/pubsubhubbub-core-0.X.html we'll have to push to gh-pages anyway. Or am I missing something?

**Comment by pfefferle** [comment]
no, you can use the gh-pages as master... see https://github.com/webfinger/assets or https://github.com/webfinger/webfinger.net

**Comment by julien51** [comment]
Great! How do I do that?

**Comment by pfefferle** [comment]
I think this is the easiest way to do so http://oli.jp/2011/github-pages-workflow/#deleting-master

**Comment by pfefferle** [comment]
but copy the readme before doing so ;)

**Comment by julien51** [comment]
Done :) Closing now!
