### ISSUE TITLE
Recommend HEAD for discovery

### ISSUE THREAD

**Issue by evanp** [pubsubhubbub/PubSubHubbub#3]
For large resources, retrieving the entire resource just to get the headers is inefficient.

It may make sense to recommend using HEAD to check for HTTP headers.

If they're not there, and the Content-Type is one of the fallback 0.3 types, use a GET and check the body for hub links.

**Comment by superfeedr** [comment]
Awesome idea!

**Comment by superfeedr** [comment]
Fixed in #7ac2e59. (for some reason, I can't close issues!)
