### ISSUE TITLE
PubSubHubbub Core 0.4: X-Hub-Signature

### ISSUE THREAD

**Issue by cweiske** [pubsubhubbub/PubSubHubbub#30]
Why is "X-Hub-Signature" prefixed with "X-"?
Isn't that considered bad practice now?

RFC 6648: Deprecating the "X-" Prefix and Similar Constructs in
Application Protocols
https://tools.ietf.org/html/rfc6648

**Comment by julien51** [comment]
It's indeed not recommend anymore which does not mean that it's bad practice. Also IIRC, the spec predates that RFC.

We may change that in the future, but I can't see any significant advantage while we'd increase complexity and decrease compatibility...
