### ISSUE TITLE
Use Content-Location rather than self-link

### ISSUE THREAD

**Issue by evanp** [pubsubhubbub/PubSubHubbub#4]
I'm not sure what the difference is, but we should probably consider using the already-standard Content-Location header rather than a self-URL.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#Content-Location

**Comment by superfeedr** [comment]
I didn't know this existed! So I'll fix this!

**Comment by julien51** [comment]
I used Link headers as per issue #2. Are you favor of using this one too?
