### ISSUE TITLE
Make PuSH a "living" spec

### ISSUE THREAD

**Issue by aaronpk** [pubsubhubbub/PubSubHubbub#42]
Let's make the PuSH spec a living spec that can take over after 0.4. This will allow future work to be done more rapidly, allowing it to keep up with other specs.

**Comment by cweiske** [comment]
Please don't. If you do, every compliant client today can be uncompliant tomorrow. You can't safely say anymore that your software fully implements PuSH because it might not be the case an hour later, when some spec update was published by some rapid thinkerer.

**Comment by voxpelli** [comment]
@cweiske A living spec needs to take that into consideration and make changes that don't break older implementations. So a living spec will probably result in more implementations being compliant than a spec that releases new versions every now and then.

**Comment by cweiske** [comment]
It's not about breaking changes. Everything is a breaking change if it changes the way the spec has to be implemented.

If you were right, then only optional sections and optional parameters could be added to a living spec.

**Comment by voxpelli** [comment]
Sounds like a definition of `living standard` is needed. Here's what WHATWG has to say about theirs: https://wiki.whatwg.org/wiki/FAQ#What_does_.22Living_Standard.22_mean.3F

**Comment by aaronpk** [comment]
Closing now that the spec is adopted as a w3c draft https://github.com/w3c/pubsubhubbub
