### ISSUE TITLE
Silent Rate-Limiting by the Google PubSubHubbub Hub?

### ISSUE THREAD

**Issue by steffenweber** [pubsubhubbub/PubSubHubbub#45]
[This is not an issue with the spec but with Google's PubSubHubbub Hub. Please let me know if there is a more appropriate place for my question.]

I'm publishing multiple feeds and I've noticed that the Google PubSubHubbub Hub seems to silently ignore all but ~ 10 randomly chosen URLs per POST request. It always replies with status code 204 which makes this issue hard to debug. I've tried sending the POST requests in batches of 10 URLs but that does not help. Sleeping for 20 (!) seconds between batches seems to help but I'll have to run more tests.

Are those rate-limits documented somewhere? Or can they be lifted? Does Superfeedr have less strict rate-limiting?

**Comment by robyn-dressler** [comment]
@steffenweber Have you found any answers to this? I'm noticing the same issue when subscribing to multiple feeds at once.

**Comment by steffenweber** [comment]
Unfortunately not, I've switched to SuperFeedr.

**Comment by maksverver** [comment]
Alex, Steffen, it would probably be helpful if either of you could give more details. For example, could you link to your feeds and mention which items are not propagated correctly?

There may be a simple explanation, but it's kind of hard to say without looking at a concrete example.

**Comment by robyn-dressler** [comment]
In my case, I believe I misidentified the problem. I was receiving 503 errors upon subscribing, which I believe was caused by some type of network issues with my app server. I have since resolved the issue.

**Comment by maksverver** [comment]
Thanks, Alex.

Since there were no further comments on the thread, I'm going to assume the issue is non-reproducible and close the bug. (This repository isn't really the right place to report problems with the Google hub anyway.)
