### ISSUE TITLE
Google Hub's Subscriber Diagnostics Seems down

### ISSUE THREAD

**Issue by tomy0000000** [pubsubhubbub/PubSubHubbub#48]
I'm not quite sure if this is the right place to report issue,
but Google Hub's "Subscriber Diagnostics" seems down from here.
Although other parts of the hub still works fine.
But diagnostics is still a heavy rotation during client development stage.
So can anyone help fix this, or perhaps provide where can I report this issue?
Thx.

**Comment by maksverver** [comment]
Hi Tomy. Thanks for reporting this! I've raised this issue at Google internally. It might take some time to investigate the issue.

**Comment by tomy0000000** [comment]
@maksverver Thanks for the raising

Also, as I've done a further investigation into the hub.
It seems like the core functionality is now also malfunctioned
after previous subscribe lease seconds gone by.
I've tried re-subscribe, but doesn't workout.

As I'll keep an eye on the hub recently,
I'll help closing this issue once the hub is repaired.
Thanks.

**Comment by tomy0000000** [comment]
The Hub Appear to Works now
Closing the issue

**Comment by maksverver** [comment]
Thanks for confirming the fix, Tomy!

I assume that means the issue you mentioned in your second comment is also fixed. If it turns out that's not the case, please open another bug.
