### ISSUE TITLE
Feature Request: Youtube push notifications for user activity on my channel

### ISSUE THREAD

**Issue by HDPacks** [pubsubhubbub/PubSubHubbub#69]
I'd like to request that the webhook API is expanded to include notifications for user activity on an authorized channel. Including new subscriptions and the username/display name of the subscriber (and email if possible), and any other user interaction on the channel if I subscribe to the webhook notification, such as comments, likes, shares, etc. Thanks

**Comment by maksverver** [comment]
Hi! It sounds like your request is about the YouTube notification API, but this repository is not about YouTube or any particular Google service; it contains the specification for the generic PubSubHubbub (now WebSub) protocol. If I misunderstood, feel free to open another issue, but please explain how your issue relates to the PubSubHubbub protocol specifically.

**Comment by HDPacks** [comment]
Would there be a more appropriate place to ask about this?

**Comment by maksverver** [comment]
Your best bet is probably to file a feature request in the YouTube Data API issue tracker with a short description of your use case: https://issuetracker.google.com/issues/new?component=186600

I can't guarantee that you will get a response though; Google is notoriously bad at responding to external requests, though that makes sense if you consider how many developers use their APIs.
